"""
留情局数据适配器
将监控数据转换为留情局情报格式
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List, Optional

logger = logging.getLogger(__name__)


class LiuqingjuAdapter:
    """留情局数据适配器"""

    def __init__(self, output_path: str = "data/liuqingju_export.json"):
        self.output_path = Path(output_path)
        self.output_path.parent.mkdir(parents=True, exist_ok=True)

    def convert_post(self, post_data: dict, generate_id: bool = True) -> dict:
        """
        转换帖子格式为留情局情报格式

        Args:
            post_data: 原始帖子数据
            generate_id: 是否生成新ID

        Returns:
            留情局格式的情报数据
        """
        if generate_id:
            post_id = f"intel_{datetime.now().strftime('%Y%m%d%H%M%S')}_{post_data.get('id', '001')[:8]}"
        else:
            post_id = post_data.get('id', f"intel_{datetime.now().strftime('%Y%m%d%H%M%S')}")

        university = post_data.get('source_university', 'Unknown')
        title = post_data.get('title', '')

        if not title.startswith(f"[{university}]"):
            title = f"[{university}] {title}"

        return {
            "id": post_id,
            "title": title,
            "tag": self._map_category(post_data.get('info_type', 'admission')),
            "tagLabel": self._map_category_label(post_data.get('info_type', 'admission')),
            "time": post_data.get('created_at', datetime.now().isoformat()),
            "views": 0,
            "content": self._clean_content(post_data.get('content', '')),
            "source": university,
            "sourceUrl": post_data.get('source_url', ''),
            "isAutoGenerated": True,
            "degreeLevel": post_data.get('degree_level', 'all'),
            "confidence": post_data.get('confidence', 0),
            "metadata": {
                "originalId": post_data.get('id'),
                "convertedAt": datetime.now().isoformat(),
                "postType": 'admission_intelligence'
            }
        }

    def _map_category(self, info_type: str) -> str:
        """映射信息类型到留情局标签"""
        mapping = {
            'admission': 'policy',
            'enrollment': 'resources',
            'deadline': 'deadline',
            'scholarship': 'scholarship',
            'general': 'essay'
        }
        return mapping.get(info_type, 'essay')

    def _map_category_label(self, info_type: str) -> str:
        """映射信息类型到留情局标签显示名称"""
        mapping = {
            'admission': 'POLICY',
            'enrollment': 'RESOURCES',
            'deadline': 'DEADLINE',
            'scholarship': 'SCHOLARSHIP',
            'general': 'ESSAY'
        }
        return mapping.get(info_type, 'ESSAY')

    def _clean_content(self, content: str, max_length: int = 2000) -> str:
        """清理内容，去除多余空白"""
        if not content:
            return ""

        lines = content.split('\n')
        cleaned_lines = []

        for line in lines:
            line = line.strip()
            if line and not line.startswith('#') and not line.startswith('```'):
                cleaned_lines.append(line)

        result = '\n'.join(cleaned_lines)

        if len(result) > max_length:
            result = result[:max_length] + '...'

        return result

    def export_posts(self, posts: List[dict], mode: str = 'merge') -> dict:
        """
        导出帖子到留情局格式

        Args:
            posts: 帖子列表
            mode: 导出模式 - 'merge' 合并, 'replace' 替换

        Returns:
            导出结果统计
        """
        if not posts:
            logger.info("没有帖子需要导出")
            return {"status": "success", "newCount": 0, "totalCount": 0}

        converted = [self.convert_post(p) for p in posts]

        existing = []
        if self.output_path.exists() and mode == 'merge':
            try:
                with open(self.output_path, 'r', encoding='utf-8') as f:
                    existing = json.load(f)
            except json.JSONDecodeError:
                logger.warning("现有数据文件格式错误，将重新创建")
                existing = []

        existing_ids = {p['title'] for p in existing}
        new_posts = [p for p in converted if p['title'] not in existing_ids]

        if mode == 'replace':
            all_posts = converted
        else:
            all_posts = new_posts + existing

        all_posts.sort(key=lambda x: x.get('time', ''), reverse=True)

        with open(self.output_path, 'w', encoding='utf-8') as f:
            json.dump(all_posts, f, ensure_ascii=False, indent=2)

        result = {
            "status": "success",
            "exportTime": datetime.now().isoformat(),
            "newCount": len(new_posts),
            "totalCount": len(all_posts),
            "outputPath": str(self.output_path)
        }

        logger.info(f"导出完成：新增 {len(new_posts)} 条，总计 {len(all_posts)} 条")
        return result

    def get_export_data(self) -> List[dict]:
        """获取导出数据"""
        if not self.output_path.exists():
            return []

        with open(self.output_path, 'r', encoding='utf-8') as f:
            return json.load(f)

    def generate_sync_script(self) -> str:
        """生成 localStorage 同步脚本"""
        posts = self.get_export_data()

        script = f"""
// ============================================
// 留情局情报数据同步脚本
// 执行时间: {datetime.now().isoformat()}
// 数据条数: {len(posts)}
// ============================================

(function() {{
    const INTELLIGENCE_KEY = 'liuqingju_intelligence';
    const SYNC_TIMESTAMP_KEY = 'liuqingju_intelligence_sync';

    const newData = {json.dumps(posts, ensure_ascii=False)};

    const existing = JSON.parse(localStorage.getItem(INTELLIGENCE_KEY) || '[]');

    const existingTitles = new Set(existing.map(p => p.title));
    const uniqueNew = newData.filter(p => !existingTitles.has(p.title));

    const merged = [...uniqueNew, ...existing];

    merged.sort((a, b) => new Date(b.time) - new Date(a.time));

    localStorage.setItem(INTELLIGENCE_KEY, JSON.stringify(merged));
    localStorage.setItem(SYNC_TIMESTAMP_KEY, '{datetime.now().isoformat()}');

    console.log(`[留情局同步] 添加 {{uniqueNew.length}} 条新情报，总计 {{merged.length}} 条`);

    return {{
        added: uniqueNew.length,
        total: merged.length,
        syncedAt: '{datetime.now().isoformat()}'
    }};
}})();
"""

        return script

    def get_supabase_format(self) -> List[dict]:
        """获取 Supabase 格式的数据"""
        posts = self.get_export_data()
        return [self._to_supabase_format(p) for p in posts]

    def _to_supabase_format(self, post: dict) -> dict:
        """转换为 Supabase 帖子格式"""
        return {
            "title": post['title'],
            "content": post.get('content', ''),
            "source_url": post.get('sourceUrl', ''),
            "source_university": post.get('source', ''),
            "info_type": post.get('tag', 'essay'),
            "degree_level": post.get('degreeLevel', 'all'),
            "is_auto_published": True,
            "view_count": post.get('views', 0),
            "created_at": post.get('time', datetime.now().isoformat())
        }
